name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Start
        run: make up

      - name: Install
        run: make install

      - name: Test
        run: make test

      - name: PHPStan
        run: make stan

      - name: CS check
        run: make cs-check
